feat: support custom url on image workers
kodadot/workers pull request #136
Opened 2023-08-09 11:17 UTC by preschian

2023-08-09 13:50 UTC, vikiival commented
Btw images can be uploaded via url ;)

2023-08-09 15:27 UTC, vikiival commented
> > Btw images can be uploaded via url ;)
> 
> 
> 
> Which "images" part do you mean?

True images word is ambigous in the context. 

https://developers.cloudflare.com/images/cloudflare-images/upload-images/upload-via-url/

2023-08-09 17:10 UTC, preschian commented
> [developers.cloudflare.com/images/cloudflare-images/upload-images/upload-via-url](https://developers.cloudflare.com/images/cloudflare-images/upload-images/upload-via-url/)

actually, that one is the same thing. since the worker is using javascript, this is to upload image to the cf-images

https://github.com/kodadot/workers/blob/cb6c5d78e20b58dc64b24bb098c163ee0a9c5d3f/image/src/utils/cloudflare-images.ts#L35-L45

if you visit this page https://developers.cloudflare.com/api/operations/cloudflare-images-upload-an-image-via-url, you can choose between cURL or javascript fetch on the top right side
![image](https://github.com/kodadot/workers/assets/734428/69403ab3-2454-4f6b-831e-a3477cc2a2ab)

2023-08-09 17:17 UTC, preschian commented
oopps sorry, I just understand what you mean

yes, already use URL to upload that. you can see it here

https://github.com/kodadot/workers/blob/cb6c5d78e20b58dc64b24bb098c163ee0a9c5d3f/image/src/utils/cloudflare-images.ts#L31-L33

2023-09-29 10:40 UTC, vikiival commented on image/package.json
> +    "start": "wrangler dev --remote",
maybe add option for dev?

2023-09-29 14:37 UTC, vikiival requested changes
Can we rename `CFI` to Image?

2023-10-13 10:20 UTC, preschian commented on image/package.json
> +    "start": "wrangler dev --remote",
updated

2023-10-13 10:20 UTC, preschian commented
> Can we rename `CFI` to Image?

I feel like `Image` is too general. Our worker name is also `image`

2023-10-13 10:29 UTC, preschian commented
I will deploy this to canary env, to test it on our UI

2023-10-17 04:15 UTC, preschian commented
@vikiival @roiLeo I will merge this, lmk if you had a concern regarding this PR

2023-10-17 04:16 UTC, merged