feat: early redirect for image
kodadot/workers pull request #20
Opened 2023-01-07 13:34 UTC by preschian

- [x] closes https://github.com/kodadot/nft-gallery/issues/4595

| before | after |
| --- | --- |
| <img width="1624" alt="Screenshot 2023-01-07 at 20 13 25" src="https://user-images.githubusercontent.com/734428/211153231-e310f7b2-ed01-4e9a-bfe4-47a211677f20.png"> | <img width="1624" alt="Screenshot 2023-01-07 at 20 12 23" src="https://user-images.githubusercontent.com/734428/211153252-f54a7767-6a0c-4e84-b511-e8f90980eebc.png"> |

on already uploaded images to cf-images and hit the fetch cache will be faster (<1s). on a new image still takes > 1s

2023-01-07 15:18 UTC, vikiival requested changes
Very nice!
Love it 💕

Smol stuff for better readability

2023-01-07 15:18 UTC, vikiival commented on image/src/index.ts
> +            '404': 1,
Create also const for this for better readablility

2023-01-07 15:18 UTC, vikiival commented on image/src/index.ts
> +          cacheTtlByStatus: {
Move whole object to constants?

2023-01-07 16:11 UTC, yangwao commented
wow, that's like 80% cut in time? 😍

<img src="https://media1.giphy.com/media/UuqIrvMItvrwcqCmZV/giphy.gif"/>

2023-01-09 11:00 UTC, vikiival approved these changes
Very nice!

2023-01-09 11:00 UTC, merged

2023-01-09 11:29 UTC, vikiival commented
Published

```
Uploaded image (2.71 sec)
Published image (1.64 sec)
  https://image.kodadot.workers.dev
Current Deployment ID: 0cd33751-e821-49d8-967b-f617056596ac
```