feat: nft-storage
kodadot/workers pull request #37
Opened 2023-03-05 04:27 UTC by preschian

related with #36

2023-03-07 14:56 UTC, yangwao commented
@vikiival

2023-03-07 17:10 UTC, vikiival commented
> @vikiival 

It miss the function otherwise i cant replace it on frontend

2023-03-07 17:11 UTC, vikiival requested changes
Wont merge until getKey is not implemented

2023-03-08 15:12 UTC, vikiival approved these changes

2023-03-24 12:36 UTC, vikiival commented on nft-storage-beta/src/index.ts
> +  }
@preschian maybe check if it's image based on mime-type?

2024-01-15 10:26 UTC, closed without merging