feat: init ssr-opengraph
kodadot/workers pull request #41
Opened 2023-03-22 16:19 UTC by preschian

related https://github.com/kodadot/nft-gallery/issues/5268

the method is quite similar
1. if the request is coming from a non-bot https://github.com/kodadot/workers/pull/41/files#diff-1860af2eaf6e2c14cc185436d808d762199ab1e9ec51fd94afe805d52bf8570eR18 it will continue the request
2. if the request is coming from a crawler (bot) it will fetch data to subsquid and then render static html https://github.com/kodadot/workers/pull/41/files#diff-1860af2eaf6e2c14cc185436d808d762199ab1e9ec51fd94afe805d52bf8570eR54

todo:
- [ ] collection detail
- [ ] rmrk2
- [ ] put `rmrk` to `@kodadot1/static`?

step to deploy:
1. after merging this PR, make sure to deploy the `prerender-opengraph` worker first
2. and then deploy `ssr-opengraph`. to avoid routes conflict https://github.com/kodadot/workers/pull/41/files#diff-50d1a6082b03f808cc776ab435488ebf63e81e82829e73e9fc76d094f2d5199aR4

additional notes:
- seems like prerender on netlify not working anymore. so, it will works on `kodadot.xyz` only

2023-03-22 17:36 UTC, vikiival requested changes
please use `uniquery` and `minipfs`

2023-03-22 17:42 UTC, vikiival commented
for the uniquery 

https://github.com/poppyseedDev/polkadot-fandom-page/blob/8274132d79f42967e992710951b27bd61dd111ac/src/pages/products/%5Bproduct%5D.tsx#LL26C9-L26C82

2023-03-23 08:56 UTC, vikiival requested changes
Really good job, small things

2023-03-23 08:56 UTC, vikiival commented on ssr-opengraph/src/utils.ts
> +  const client = getClient();
If you want to use fetch on client you need pass prefix here 😇

2023-03-23 12:45 UTC, yangwao commented
Somewhre on gaming nft marketplaces I've seen they've been pushing different numbers on card from collections, can create on that issue once I spot it again, that would be amazing to have it, otherwise looking forward to deploying this to beta & production

2023-03-23 13:36 UTC, vikiival commented on ssr-opengraph/src/utils.ts
> +  rmrk: 'https://squid.subsquid.io/rubick/graphql',
```suggestion
  rmrk: INDEXERS['ksm'],
```

2023-03-23 14:00 UTC, vikiival approved these changes

2023-03-23 14:00 UTC, merged

2023-03-24 13:25 UTC, vikiival commented
cc @preschian 

➜  prerender-opengraph git:(main) ✗ npx wrangler publish
 ⛅️ wrangler 2.1.13 (update available 2.13.0)
-------------------------------------------------------
Total Upload: 2.34 KiB / gzip: 1.02 KiB
Uploaded prerender-opengraph (3.64 sec)
Published prerender-opengraph (15.99 sec)
  kodadot.xyz/rmrk/detail/*
  kodadot.xyz/bsx/detail/*
  kodadot.xyz/snek/detail/*
  kodadot.xyz/glmr/gallery/*
  kodadot.xyz/glmr/detail/*
➜  prerender-opengraph git:(main) ✗ cd ../ssr-opengraph
➜  ssr-opengraph git:(main) ✗ npx wrangler publish
 ⛅️ wrangler 2.13.0
--------------------

✘ [ERROR] Missing entry-point: The entry-point should be specified via the command line (e.g. `wrangler publish path/to/script`) or the `main` config field.


If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose

2023-03-24 15:52 UTC, vikiival commented
fixed in 6ee53cabff818bcaf720e8738f30c188b1d7bddf